title: Test
seo_title: '@auto'
seo_description: '@default'
seo_og_image: '@default'
seo_og_title: '@auto'
seo_og_description: '@auto'
seo_twitter_card: '@default'
seo_twitter_summary_image: '@default'
seo_twitter_title: '@auto'
seo_twitter_description: '@auto'
seo_canonical_type: '@default'
seo_noindex: '@default'
seo_nofollow: '@default'
seo_sitemap_enabled: '@default'
seo_sitemap_priority: '@default'
seo_sitemap_change_frequency: '@default'
seo_json_ld: '@default'
updated_by: b1943171-0e5c-4c46-bc42-c39e33663975
updated_at: 1654031392
blueprint: categories
